### ISSUE TITLE
How are files uploaded?

### ISSUE THREAD

**Issue by RiverMersey** [DoESLiverpool/somewhere-safe#2]
How can we upload files to this "somewhere-safe" thread? 

On trying to use the "upload file" button, it responds with, "feature disabled".

**Comment by johnmckerrell** [comment]
It looks like you weren't a member of the DoES Liverpool organisation on GitHub so I've invited you now and that should give you permission to upload to the repo. If you can confirm that has worked and then feel free to close this ticket.

**Comment by RiverMersey** [comment]
Many thanks. Just tried again to upload and still have the same error message, though.

**Comment by johnmckerrell** [comment]
You need to accept the invitation to be a member. You should have received an email or you might see something on this page: https://github.com/DoESLiverpool/

**Comment by RiverMersey** [comment]
Yes, many thanks. Seems that the invitation email went to spam. Now that I've accepted the invite, I can now post files into the GitHub.
